In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
data=pd.read_csv("Admission_Predict.csv")
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [3]:
data.isnull().any()

Serial No.           False
GRE Score            False
TOEFL Score          False
University Rating    False
SOP                  False
LOR                  False
CGPA                 False
Research             False
Chance of Admit      False
dtype: bool

In [4]:
data.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [5]:
x=data.iloc[:,1:8].values
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]])

In [6]:
y=data.iloc[:,8:].values
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.61],
       [0.57],
       [0.68],
       [0.78],
       [0.94],
       [0.96],
       [0.93],
       [0.84],
       [0.74],
       [0.72],
       [0.74],
       [0.64],
       [0.44],
       [0.46],
       [0.5 ],
       [0.96],
       [0.92],
       [0.92],
       [0.94],
       [0.76],
       [0.72],
       [0.66],
       [0.64],
       [0.74],
       [0.64],
       [0.38],
       [0.34],
       [0.44],
       [0.36],
       [0.42],
       [0.48],
       [0.86],
       [0.9 ],
       [0.79],
       [0.71],
       [0.64],
       [0.62],
       [0.57],
       [0.74],
       [0.69],
       [0.87],
       [0.91],
       [0.93],
       [0.68],
       [0.61],
       [0.69],
       [0.62],
       [0.72],
       [0.59],
       [0.66],
       [0.56],
       [0.45],
       [0.47],
       [0.71],
       [0.94],
       [0.94],
       [0.57],
       [0.61],
       [0.57],
       [0.64],
       [0.85],
       [0.78],
       [0.84],
       [0.92],
       [0.96],
       [0.77],
       [0.71],
       [0.79],
       [0.89],
       [0.82],
       [0.76],
       [0.71],
       [0.8 ],
       [0.78],
       [0.84],
       [0.9 ],
       [0.92],
       [0.97],
       [0.8 ],
       [0.81],
       [0.75],
       [0.83],
       [0.96],
       [0.79],
       [0.93],
       [0.94],
       [0.86],
       [0.79],
       [0.8 ],
       [0.77],
       [0.7 ],
       [0.65],
       [0.61],
       [0.52],
       [0.57],
       [0.53],
       [0.67],
       [0.68],
       [0.81],
       [0.78],
       [0.65],
       [0.64],
       [0.64],
       [0.65],
       [0.68],
       [0.89],
       [0.86],
       [0.89],
       [0.87],
       [0.85],
       [0.9 ],
       [0.82],
       [0.72],
       [0.73],
       [0.71],
       [0.71],
       [0.68],
       [0.75],
       [0.72],
       [0.89],
       [0.84],
       [0.93],
       [0.93],
       [0.88],
       [0.9 ],
       [0.87],
       [0.86],
       [0.94],
       [0.77],
       [0.78],
       [0.73],
       [0.73],
       [0.7 ],
       [0.72],
       [0.73],
       [0.72],
       [0.97],
       [0.97],
       [0.69],
       [0.57],
       [0.63],
       [0.66],
       [0.64],
       [0.68],
       [0.79],
       [0.82],
       [0.95],
       [0.96],
       [0.94],
       [0.93],
       [0.91],
       [0.85],
       [0.84],
       [0.74],
       [0.76],
       [0.75],
       [0.76],
       [0.71],
       [0.67],
       [0.61],
       [0.63],
       [0.64],
       [0.71],
       [0.82],
       [0.73],
       [0.74],
       [0.69],
       [0.64],
       [0.91],
       [0.88],
       [0.85],
       [0.86],
       [0.7 ],
       [0.59],
       [0.6 ],
       [0.65],
       [0.7 ],
       [0.76],
       [0.63],
       [0.81],
       [0.72],
       [0.71],
       [0.8 ],
       [0.77],
       [0.74],
       [0.7 ],
       [0.71],
       [0.93],
       [0.85],
       [0.79],
       [0.76],
       [0.78],
       [0.77],
       [0.9 ],
       [0.87],
       [0.71],
       [0.7 ],
       [0.7 ],
       [0.75],
       [0.71],
       [0.72],
       [0.73],
       [0.83],
       [0.77],
       [0.72],
       [0.54],
       [0.49],
       [0.52],
       [0.58],
       [0.78],
       [0.89],
       [0.7 ],
       [0.66],
       [0.67],
       [0.68],
       [0.8 ],
       [0.81],
       [0.8 ],
       [0.94],
       [0.93],
       [0.92],
       [0.89],
       [0.82],
       [0.79],
       [0.58],
       [0.56],
       [0.56],
       [0.64],
       [0.61],
       [0.68],
       [0.76],
       [0.86],
       [0.9 ],
       [0.71],
       [0.62],
       [0.66],
       [0.65],
       [0.73],
       [0.62],
       [0.74],
       [0.79],
       [0.8 ],
       [0.69],
       [0.7 ],
       [0.76],
       [0.84],
       [0.78],
       [0.67],
       [0.66],
       [0.65],
       [0.54],
       [0.58],
       [0.79],
       [0.8 ],
       [0.75],
       [0.73],
       [0.72],
       [0.62],
       [0.67],
       [0.81],
       [0.63],
       [0.69],
       [0.8 ],
       [0.43],
       [0.8 ],
       [0.73],
       [0.75],
       [0.71],
       [0.73],
       [0.83],
       [0.72],
       [0.94],
       [0.81],
       [0.81],
       [0.75],
       [0.79],
       [0.58],
       [0.59],
       [0.47],
       [0.49],
       [0.47],
       [0.42],
       [0.57],
       [0.62],
       [0.74],
       [0.73],
       [0.64],
       [0.63],
       [0.59],
       [0.73],
       [0.79],
       [0.68],
       [0.7 ],
       [0.81],
       [0.85],
       [0.93],
       [0.91],
       [0.69],
       [0.77],
       [0.86],
       [0.74],
       [0.57],
       [0.51],
       [0.67],
       [0.72],
       [0.89],
       [0.95],
       [0.79],
       [0.39],
       [0.38],
       [0.34],
       [0.47],
       [0.56],
       [0.71],
       [0.78],
       [0.73],
       [0.82],
       [0.62],
       [0.96],
       [0.96],
       [0.46],
       [0.53],
       [0.49],
       [0.76],
       [0.64],
       [0.71],
       [0.84],
       [0.77],
       [0.89],
       [0.82],
       [0.84],
       [0.91],
       [0.67],
       [0.95]])

In [7]:
x.shape

(400, 7)

In [8]:
y.shape

(400, 1)

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [10]:
x_train.shape

(320, 7)

In [11]:
y_train.shape

(320, 1)

In [12]:
y_train=(y_train>0.5)

In [13]:
y_test=(y_test>0.5)

In [14]:
cls=RandomForestClassifier(n_estimators =10)

In [15]:
lr = cls.fit(x_train,y_train)

<ipython-input-15-6075d2743e24>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  lr = cls.fit(x_train,y_train)

In [16]:
y_pred = lr.predict(x_test)

In [17]:
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False])

In [18]:
y_test

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False]])

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 2,  3],
       [ 0, 75]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print("Accuracy score:",accuracy_score(y_test,y_pred)*100)
print("Recall score:",recall_score(y_test,y_pred)*100)
print("Precision score:",precision_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred)*100)

Accuracy score: 96.25
Recall score: 100.0
Precision score: 96.15384615384616
F1 score: 98.0392156862745